version: '3.5'

services:

  # php-cli
  php-cli:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
    - .:/var/www
    - composer:/root/.composer/cache

  # redis
  redis-cli:
    image: redis:6.0-rc1-alpine
    volumes:
    - redis:/data
    ports:
    - 6379:6379
    # command: redis-server --requirepass secret

volumes:
  composer:
  redis: